name: 'NPM Publish'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-npm:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
      - run: 'npm ci --ignore-scripts'
      - run: 'npm run test'
      - run: 'echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV'
      - run: 'npm version --no-git-tag-version ${{ env.RELEASE_VERSION }}'
      - run: 'npm publish'
        env:
          NODE_AUTH_TOKEN: '${{secrets.npm_token}}'
